# backend/rag/drug_aliases.py
#
# Brand-name → generic-name mapping used for query normalisation.
# All keys and values are lowercase.
from typing import Dict, List

BRAND_TO_GENERIC: Dict[str, str] = {
    # Pain / Anti-inflammatory
    "advil":       "ibuprofen",
    "motrin":      "ibuprofen",
    "nuprin":      "ibuprofen",
    "tylenol":     "acetaminophen",
    "panadol":     "acetaminophen",
    "bayer":       "aspirin",
    "ecotrin":     "aspirin",
    "aleve":       "naproxen",
    "naprosyn":    "naproxen",
    "ultram":      "tramadol",
    "conzip":      "tramadol",
    "oxycontin":   "oxycodone",
    "roxicodone":  "oxycodone",
    "vicodin":     "hydrocodone",
    "norco":       "hydrocodone",
    "lortab":      "hydrocodone",
    "neurontin":   "gabapentin",
    "lyrica":      "pregabalin",
    "celebrex":    "celecoxib",
    # Antibiotics
    "amoxil":      "amoxicillin",
    "trimox":      "amoxicillin",
    "zithromax":   "azithromycin",
    "z-pack":      "azithromycin",
    "zpack":       "azithromycin",
    "vibramycin":  "doxycycline",
    "cipro":       "ciprofloxacin",
    "flagyl":      "metronidazole",
    "cleocin":     "clindamycin",
    "augmentin":   "amoxicillin-clavulanate",
    "bactrim":     "trimethoprim-sulfamethoxazole",
    "septra":      "trimethoprim-sulfamethoxazole",
    "levaquin":    "levofloxacin",
    # Antivirals / Antifungals
    "zovirax":     "acyclovir",
    "valtrex":     "valacyclovir",
    "tamiflu":     "oseltamivir",
    "diflucan":    "fluconazole",
    # Psychiatric / Neurological
    "zoloft":      "sertraline",
    "lexapro":     "escitalopram",
    "prozac":      "fluoxetine",
    "sarafem":     "fluoxetine",
    "wellbutrin":  "bupropion",
    "zyban":       "bupropion",
    "effexor":     "venlafaxine",
    "cymbalta":    "duloxetine",
    "xanax":       "alprazolam",
    "ativan":      "lorazepam",
    "klonopin":    "clonazepam",
    "seroquel":    "quetiapine",
    "abilify":     "aripiprazole",
    "eskalith":    "lithium",
    "lithobid":    "lithium",
    "lamictal":    "lamotrigine",
    "ambien":      "zolpidem",
    "edluar":      "zolpidem",
    "desyrel":     "trazodone",
    # ADHD
    "adderall":    "amphetamine",
    "ritalin":     "methylphenidate",
    "concerta":    "methylphenidate",
    "vyvanse":     "lisdexamfetamine",
    "strattera":   "atomoxetine",
    # Cardiovascular
    "zestril":     "lisinopril",
    "prinivil":    "lisinopril",
    "lopressor":   "metoprolol",
    "toprol":      "metoprolol",
    "lipitor":     "atorvastatin",
    "norvasc":     "amlodipine",
    "cozaar":      "losartan",
    "hyzaar":      "losartan",
    "coumadin":    "warfarin",
    "jantoven":    "warfarin",
    "plavix":      "clopidogrel",
    "lasix":       "furosemide",
    "aldactone":   "spironolactone",
    "coreg":       "carvedilol",
    "lanoxin":     "digoxin",
    "eliquis":     "apixaban",
    "xarelto":     "rivaroxaban",
    # Diabetes
    "glucophage":  "metformin",
    "fortamet":    "metformin",
    "lantus":      "insulin glargine",
    "basaglar":    "insulin glargine",
    "toujeo":      "insulin glargine",
    "humalog":     "insulin lispro",
    "ozempic":     "semaglutide",
    "wegovy":      "semaglutide",
    "rybelsus":    "semaglutide",
    "mounjaro":    "tirzepatide",
    "zepbound":    "tirzepatide",
    "jardiance":   "empagliflozin",
    "farxiga":     "dapagliflozin",
    "januvia":     "sitagliptin",
    "glucotrol":   "glipizide",
    # Respiratory / Allergy
    "proventil":   "albuterol",
    "ventolin":    "albuterol",
    "proair":      "albuterol",
    "singulair":   "montelukast",
    "flonase":     "fluticasone",
    "pulmicort":   "budesonide",
    "rhinocort":   "budesonide",
    "spiriva":     "tiotropium",
    "zyrtec":      "cetirizine",
    "claritin":    "loratadine",
    "allegra":     "fexofenadine",
    "benadryl":    "diphenhydramine",
    "vistaril":    "hydroxyzine",
    "atarax":      "hydroxyzine",
    # GI
    "prilosec":    "omeprazole",
    "protonix":    "pantoprazole",
    "nexium":      "esomeprazole",
    "pepcid":      "famotidine",
    "zofran":      "ondansetron",
    "imodium":     "loperamide",
    "miralax":     "polyethylene glycol",
    "reglan":      "metoclopramide",
    "bentyl":      "dicyclomine",
    # Thyroid / Hormones
    "synthroid":   "levothyroxine",
    "levoxyl":     "levothyroxine",
    "cytomel":     "liothyronine",
    "estrace":     "estradiol",
    "prometrium":  "progesterone",
    "depo-provera":"medroxyprogesterone",
    "provera":     "medroxyprogesterone",
    "clomid":      "clomiphene",
    "femara":      "letrozole",
    "aygestin":    "norethindrone",
    # Men's health
    "viagra":      "sildenafil",
    "revatio":     "sildenafil",
    "cialis":      "tadalafil",
    "adcirca":     "tadalafil",
    "proscar":     "finasteride",
    "propecia":    "finasteride",
    "avodart":     "dutasteride",
    "flomax":      "tamsulosin",
    # Dermatology
    "retin-a":     "tretinoin",
    "renova":      "tretinoin",
    "accutane":    "isotretinoin",
    "absorica":    "isotretinoin",
    "differin":    "adapalene",
    "finacea":     "azelaic acid",
    "protopic":    "tacrolimus",
    "temovate":    "clobetasol",
    "kenalog":     "triamcinolone",
    "desowen":     "desonide",
    "nizoral":     "ketoconazole",
    "rogaine":     "minoxidil",
    "xalatan":     "latanoprost",
    # Bone / Joint / Rheumatology
    "fosamax":     "alendronate",
    "colcrys":     "colchicine",
    "zyloprim":    "allopurinol",
    "trexall":     "methotrexate",
    "plaquenil":   "hydroxychloroquine",
    # Neurology
    "aricept":     "donepezil",
    "namenda":     "memantine",
    "sinemet":     "carbidopa-levodopa",
    "requip":      "ropinirole",
    # Urology
    "ditropan":    "oxybutynin",
    "vesicare":    "solifenacin",
    # Oncology / Hormone therapy
    "nolvadex":    "tamoxifen",
    "arimidex":    "anastrozole",
    # Addiction / SUD
    "narcan":      "naloxone",
    "kloxxado":    "naloxone",
    "vivitrol":    "naltrexone",
    "revia":       "naltrexone",
    "suboxone":    "buprenorphine",
    "subutex":     "buprenorphine",
    "chantix":     "varenicline",
    "champix":     "varenicline",
    # HIV
    "tivicay":     "dolutegravir",
    "viread":      "tenofovir",
    # OTC / Supplements
    "flintstones": "folic acid",
}

# Reverse mapping: generic → canonical display name for response messages
_CANONICAL: Dict[str, str] = {
    "ibuprofen":                    "Ibuprofen",
    "acetaminophen":                "Acetaminophen",
    "aspirin":                      "Aspirin",
    "naproxen":                     "Naproxen",
    "tramadol":                     "Tramadol",
    "oxycodone":                    "Oxycodone",
    "hydrocodone":                  "Hydrocodone",
    "gabapentin":                   "Gabapentin",
    "pregabalin":                   "Pregabalin",
    "celecoxib":                    "Celecoxib",
    "amoxicillin":                  "Amoxicillin",
    "azithromycin":                 "Azithromycin",
    "doxycycline":                  "Doxycycline",
    "ciprofloxacin":                "Ciprofloxacin",
    "metronidazole":                "Metronidazole",
    "clindamycin":                  "Clindamycin",
    "levofloxacin":                 "Levofloxacin",
    "acyclovir":                    "Acyclovir",
    "valacyclovir":                 "Valacyclovir",
    "oseltamivir":                  "Oseltamivir",
    "fluconazole":                  "Fluconazole",
    "sertraline":                   "Sertraline",
    "escitalopram":                 "Escitalopram",
    "fluoxetine":                   "Fluoxetine",
    "bupropion":                    "Bupropion",
    "venlafaxine":                  "Venlafaxine",
    "duloxetine":                   "Duloxetine",
    "alprazolam":                   "Alprazolam",
    "lorazepam":                    "Lorazepam",
    "clonazepam":                   "Clonazepam",
    "quetiapine":                   "Quetiapine",
    "aripiprazole":                 "Aripiprazole",
    "lithium":                      "Lithium",
    "lamotrigine":                  "Lamotrigine",
    "zolpidem":                     "Zolpidem",
    "trazodone":                    "Trazodone",
    "amphetamine":                  "Adderall (amphetamine)",
    "methylphenidate":              "Methylphenidate",
    "atomoxetine":                  "Atomoxetine",
    "lisinopril":                   "Lisinopril",
    "metoprolol":                   "Metoprolol",
    "atorvastatin":                 "Atorvastatin",
    "amlodipine":                   "Amlodipine",
    "losartan":                     "Losartan",
    "warfarin":                     "Warfarin",
    "clopidogrel":                  "Clopidogrel",
    "furosemide":                   "Furosemide",
    "spironolactone":               "Spironolactone",
    "carvedilol":                   "Carvedilol",
    "digoxin":                      "Digoxin",
    "apixaban":                     "Apixaban",
    "rivaroxaban":                  "Rivaroxaban",
    "metformin":                    "Metformin",
    "insulin glargine":             "Insulin Glargine",
    "insulin lispro":               "Insulin Lispro",
    "semaglutide":                  "Semaglutide",
    "tirzepatide":                  "Tirzepatide",
    "albuterol":                    "Albuterol",
    "montelukast":                  "Montelukast",
    "fluticasone":                  "Fluticasone",
    "budesonide":                   "Budesonide",
    "tiotropium":                   "Tiotropium",
    "cetirizine":                   "Cetirizine",
    "loratadine":                   "Loratadine",
    "fexofenadine":                 "Fexofenadine",
    "diphenhydramine":              "Diphenhydramine",
    "hydroxyzine":                  "Hydroxyzine",
    "omeprazole":                   "Omeprazole",
    "pantoprazole":                 "Pantoprazole",
    "esomeprazole":                 "Esomeprazole",
    "famotidine":                   "Famotidine",
    "ondansetron":                  "Ondansetron",
    "loperamide":                   "Loperamide",
    "levothyroxine":                "Levothyroxine",
    "sildenafil":                   "Sildenafil",
    "tadalafil":                    "Tadalafil",
    "finasteride":                  "Finasteride",
    "tretinoin":                    "Tretinoin",
    "isotretinoin":                 "Isotretinoin",
    "naloxone":                     "Naloxone",
    "buprenorphine":                "Buprenorphine",
    "varenicline":                  "Varenicline",
    "dolutegravir":                 "Dolutegravir",
    "tenofovir":                    "Tenofovir",
}

# A curated list used in the "no drugs in corpus" fallback message.
EXAMPLE_CORPUS_DRUGS: List[str] = [
    "Ibuprofen", "Metformin", "Lisinopril", "Sertraline", "Atorvastatin",
    "Fluoxetine", "Metoprolol", "Tretinoin", "Isotretinoin", "Semaglutide",
]


def normalize_drug_name(name: str) -> str:
    """
    Map a brand or generic name to its canonical generic form (lowercase).
    Returns the input unchanged (lowercased) if not found in the mapping.
    """
    key = name.lower().strip()
    return BRAND_TO_GENERIC.get(key, key)


def display_name(generic: str) -> str:
    """Return a human-readable capitalised name for a generic drug."""
    return _CANONICAL.get(generic.lower(), generic.title())
